// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTrwuwsC1qmEuU-jtp_ixfdl_HqsteA0',
    appId: '1:982967205255:web:6f6a16cdf0e9ac6863e722',
    messagingSenderId: '982967205255',
    projectId: 'student-d61a6',
    authDomain: 'student-d61a6.firebaseapp.com',
    storageBucket: 'student-d61a6.appspot.com',
    measurementId: 'G-VGKYMB168E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBESr698D2Xa-u6BrbdwQeWkZPnrZ97M',
    appId: '1:982967205255:android:ffc4b34759ac1a0363e722',
    messagingSenderId: '982967205255',
    projectId: 'student-d61a6',
    storageBucket: 'student-d61a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQirx95WXP7-bwi_5pq4_5GUGPqyi_jRA',
    appId: '1:982967205255:ios:8abff2bc9ebde9d463e722',
    messagingSenderId: '982967205255',
    projectId: 'student-d61a6',
    storageBucket: 'student-d61a6.appspot.com',
    iosClientId: '982967205255-f88tbvqhtjrih6vok1kmvr240aneek2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.student',
  );
}
